FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY turbo.json ./

COPY packages/tsconfig ./packages/tsconfig
COPY packages/ui-components ./packages/ui-components
COPY packages/utils ./packages/utils

COPY apps/web ./apps/web

# RUN yarn install
# RUN yarn build --workspace=@repo/utils

WORKDIR /app/apps/web

EXPOSE 3000

CMD ["yarn","dev"]