FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY turbo.json ./
COPY packages/tsconfig ./packages/tsconfig
COPY packages/ui-components ./packages/ui-components
COPY apps/docs ./apps/docs

RUN npm install

WORKDIR /app/apps/docs

CMD ["npm", "run", "dev"]