#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run linting
npm run lint
if [ $? -ne 0 ]; then
  echo "Linting failed. Commit aborted."
  exit 1
fi

# Run tests
# npm run test
# if [ $? -ne 0 ]; then
#   echo "Tests failed. Commit aborted."
#   exit 1
# fi